name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build:
    uses: kirandevops1993/VS-BUILD-REUSABLE-REPO-/.github/workflows/vsbuild-reusable.yml@main
    with:
      solution_path: 'AspnetCoreMvcFull.sln'
      build_configuration: 'Release'

